
// This file has been generated by the GUI designer. Do not modify.
namespace BangSharp.Client
{
	public partial class ServerWindow
	{
		private global::Gtk.VBox vbox7;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Frame frame6;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.Table table4;
		private global::Gtk.Label label12;
		private global::Gtk.Label label13;
		private global::Gtk.Label label19;
		private global::Gtk.Label serverDescriptionLabel;
		private global::Gtk.Label serverInterfaceVersionLabel;
		private global::Gtk.Label serverNameLabel;
		private global::Gtk.Label GtkLabel5;
		private global::Gtk.Frame frame7;
		private global::Gtk.Alignment GtkAlignment4;
		private global::Gtk.VBox vbox9;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.NodeView sessionsView;
		private global::Gtk.HButtonBox hbuttonbox6;
		private global::Gtk.Button createSessionButton;
		private global::Gtk.Button joinSessionButton;
		private global::Gtk.Button replaceButton;
		private global::Gtk.Button spectateSessionButton;
		private global::Gtk.Label GtkLabel6;
		private global::BangSharp.Client.SessionInfoWidget sessionInfoWidget;
		private global::Gtk.HButtonBox hbuttonbox5;
		private global::Gtk.Button disconnectButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BangSharp.Client.ServerWindow
			this.Name = "BangSharp.Client.ServerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Server Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DestroyWithParent = true;
			// Container child BangSharp.Client.ServerWindow.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 464;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
			this.table4.Add (this.label12);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table4 [this.label12]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Description:");
			this.table4.Add (this.label13);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table4 [this.label13]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xalign = 0F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Interface Version:");
			this.table4.Add (this.label19);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table4 [this.label19]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.serverDescriptionLabel = new global::Gtk.Label ();
			this.serverDescriptionLabel.Name = "serverDescriptionLabel";
			this.table4.Add (this.serverDescriptionLabel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4 [this.serverDescriptionLabel]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.serverInterfaceVersionLabel = new global::Gtk.Label ();
			this.serverInterfaceVersionLabel.Name = "serverInterfaceVersionLabel";
			this.table4.Add (this.serverInterfaceVersionLabel);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4 [this.serverInterfaceVersionLabel]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.serverNameLabel = new global::Gtk.Label ();
			this.serverNameLabel.Name = "serverNameLabel";
			this.table4.Add (this.serverNameLabel);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table4 [this.serverNameLabel]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment3.Add (this.table4);
			this.frame6.Add (this.GtkAlignment3);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Server Information</b>");
			this.GtkLabel5.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel5;
			this.vbox8.Add (this.frame6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.frame6]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.sessionsView = new global::Gtk.NodeView ();
			this.sessionsView.CanFocus = true;
			this.sessionsView.Name = "sessionsView";
			this.GtkScrolledWindow2.Add (this.sessionsView);
			this.vbox9.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.GtkScrolledWindow2]));
			w11.Position = 0;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbuttonbox6 = new global::Gtk.HButtonBox ();
			this.hbuttonbox6.Name = "hbuttonbox6";
			this.hbuttonbox6.Spacing = 6;
			this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.createSessionButton = new global::Gtk.Button ();
			this.createSessionButton.CanFocus = true;
			this.createSessionButton.Name = "createSessionButton";
			this.createSessionButton.UseUnderline = true;
			this.createSessionButton.Label = global::Mono.Unix.Catalog.GetString ("Create");
			this.hbuttonbox6.Add (this.createSessionButton);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.createSessionButton]));
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.joinSessionButton = new global::Gtk.Button ();
			this.joinSessionButton.Sensitive = false;
			this.joinSessionButton.CanFocus = true;
			this.joinSessionButton.Name = "joinSessionButton";
			this.joinSessionButton.UseUnderline = true;
			this.joinSessionButton.Label = global::Mono.Unix.Catalog.GetString ("Join");
			this.hbuttonbox6.Add (this.joinSessionButton);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.joinSessionButton]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.replaceButton = new global::Gtk.Button ();
			this.replaceButton.Sensitive = false;
			this.replaceButton.CanFocus = true;
			this.replaceButton.Name = "replaceButton";
			this.replaceButton.UseUnderline = true;
			this.replaceButton.Label = global::Mono.Unix.Catalog.GetString ("Replace");
			this.hbuttonbox6.Add (this.replaceButton);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.replaceButton]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.spectateSessionButton = new global::Gtk.Button ();
			this.spectateSessionButton.Sensitive = false;
			this.spectateSessionButton.CanFocus = true;
			this.spectateSessionButton.Name = "spectateSessionButton";
			this.spectateSessionButton.UseUnderline = true;
			this.spectateSessionButton.Label = global::Mono.Unix.Catalog.GetString ("Spectate");
			this.hbuttonbox6.Add (this.spectateSessionButton);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.spectateSessionButton]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox9.Add (this.hbuttonbox6);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbuttonbox6]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.GtkAlignment4.Add (this.vbox9);
			this.frame7.Add (this.GtkAlignment4);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Sessions</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel6;
			this.vbox8.Add (this.frame7);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.frame7]));
			w19.Position = 1;
			this.hpaned1.Add (this.vbox8);
			global::Gtk.Paned.PanedChild w20 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox8]));
			w20.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.sessionInfoWidget = new global::BangSharp.Client.SessionInfoWidget ();
			this.sessionInfoWidget.Events = ((global::Gdk.EventMask)(256));
			this.sessionInfoWidget.Name = "sessionInfoWidget";
			this.hpaned1.Add (this.sessionInfoWidget);
			this.vbox7.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hpaned1]));
			w22.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbuttonbox5 = new global::Gtk.HButtonBox ();
			this.hbuttonbox5.Name = "hbuttonbox5";
			this.hbuttonbox5.Spacing = 6;
			this.hbuttonbox5.BorderWidth = ((uint)(3));
			this.hbuttonbox5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
			this.disconnectButton = new global::Gtk.Button ();
			this.disconnectButton.CanFocus = true;
			this.disconnectButton.Name = "disconnectButton";
			this.disconnectButton.UseStock = true;
			this.disconnectButton.UseUnderline = true;
			this.disconnectButton.Label = "gtk-disconnect";
			this.hbuttonbox5.Add (this.disconnectButton);
			global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.disconnectButton]));
			w23.Expand = false;
			w23.Fill = false;
			this.vbox7.Add (this.hbuttonbox5);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbuttonbox5]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 941;
			this.DefaultHeight = 608;
			this.Show ();
			this.DestroyEvent += new global::Gtk.DestroyEventHandler (this.OnDestroyEvent);
			this.createSessionButton.Clicked += new global::System.EventHandler (this.OnCreateSessionButtonClicked);
			this.joinSessionButton.Clicked += new global::System.EventHandler (this.OnJoinSessionButtonClicked);
			this.replaceButton.Clicked += new global::System.EventHandler (this.OnReplaceButtonClicked);
			this.spectateSessionButton.Clicked += new global::System.EventHandler (this.OnSpectateSessionButtonClicked);
			this.disconnectButton.Clicked += new global::System.EventHandler (this.OnDisconnectButtonClicked);
		}
	}
}
