
// This file has been generated by the GUI designer. Do not modify.
namespace BangSharp.Client
{
	public partial class ServerListWindow
	{
		private global::Gtk.Frame frame5;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox vbox11;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView serverList;
		private global::Gtk.HButtonBox hbuttonbox7;
		private global::Gtk.Button connectButton;
		private global::Gtk.Button addServerButton;
		private global::Gtk.Button removeServerButton;
		private global::Gtk.Label GtkLabel2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BangSharp.Client.ServerListWindow
			this.Name = "BangSharp.Client.ServerListWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Connect to server...");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.DestroyWithParent = true;
			// Container child BangSharp.Client.ServerListWindow.Gtk.Container+ContainerChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.serverList = new global::Gtk.NodeView ();
			this.serverList.CanFocus = true;
			this.serverList.Name = "serverList";
			this.GtkScrolledWindow.Add (this.serverList);
			this.vbox11.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbuttonbox7 = new global::Gtk.HButtonBox ();
			this.hbuttonbox7.Name = "hbuttonbox7";
			this.hbuttonbox7.Spacing = 6;
			this.hbuttonbox7.BorderWidth = ((uint)(3));
			this.hbuttonbox7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox7.Gtk.ButtonBox+ButtonBoxChild
			this.connectButton = new global::Gtk.Button ();
			this.connectButton.Sensitive = false;
			this.connectButton.CanDefault = true;
			this.connectButton.CanFocus = true;
			this.connectButton.Name = "connectButton";
			this.connectButton.UseStock = true;
			this.connectButton.UseUnderline = true;
			this.connectButton.Label = "gtk-connect";
			this.hbuttonbox7.Add (this.connectButton);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox7 [this.connectButton]));
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbuttonbox7.Gtk.ButtonBox+ButtonBoxChild
			this.addServerButton = new global::Gtk.Button ();
			this.addServerButton.CanFocus = true;
			this.addServerButton.Name = "addServerButton";
			this.addServerButton.UseStock = true;
			this.addServerButton.UseUnderline = true;
			this.addServerButton.Label = "gtk-add";
			this.hbuttonbox7.Add (this.addServerButton);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox7 [this.addServerButton]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbuttonbox7.Gtk.ButtonBox+ButtonBoxChild
			this.removeServerButton = new global::Gtk.Button ();
			this.removeServerButton.Sensitive = false;
			this.removeServerButton.CanFocus = true;
			this.removeServerButton.Name = "removeServerButton";
			this.removeServerButton.UseStock = true;
			this.removeServerButton.UseUnderline = true;
			this.removeServerButton.Label = "gtk-remove";
			this.hbuttonbox7.Add (this.removeServerButton);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox7 [this.removeServerButton]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox11.Add (this.hbuttonbox7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbuttonbox7]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.GtkAlignment.Add (this.vbox11);
			this.frame5.Add (this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Server List</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel2;
			this.Add (this.frame5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 347;
			this.DefaultHeight = 229;
			this.connectButton.HasDefault = true;
			this.Show ();
			this.connectButton.Clicked += new global::System.EventHandler (this.OnConnectButtonClicked);
			this.addServerButton.Clicked += new global::System.EventHandler (this.OnAddServerButtonClicked);
			this.removeServerButton.Clicked += new global::System.EventHandler (this.OnRemoveServerButtonClicked);
		}
	}
}
