
// This file has been generated by the GUI designer. Do not modify.
namespace BangSharp.Client
{
	public partial class SessionWindow
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.HPaned hpaned2;
		private global::BangSharp.Client.SessionInfoWidget sessionInfoWidget;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.VBox vbox5;
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		private global::Gtk.TextView chatView;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Entry chatEntry;
		private global::Gtk.Button chatSendButton;
		private global::Gtk.Label GtkLabel7;
		private global::Gtk.HButtonBox hbuttonbox3;
		private global::Gtk.Button startGameButton;
		private global::Gtk.Button disconnectButton;
		private global::Gtk.Button endSessionButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BangSharp.Client.SessionWindow
			this.Name = "BangSharp.Client.SessionWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Session Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 900;
			this.DefaultHeight = 650;
			// Container child BangSharp.Client.SessionWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 629;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.sessionInfoWidget = new global::BangSharp.Client.SessionInfoWidget ();
			this.sessionInfoWidget.Events = ((global::Gdk.EventMask)(256));
			this.sessionInfoWidget.Name = "sessionInfoWidget";
			this.hpaned2.Add (this.sessionInfoWidget);
			global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.sessionInfoWidget]));
			w1.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.chatView = new global::Gtk.TextView ();
			this.chatView.CanFocus = true;
			this.chatView.Name = "chatView";
			this.chatView.Editable = false;
			this.chatView.CursorVisible = false;
			this.chatView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow4.Add (this.chatView);
			this.vbox5.Add (this.GtkScrolledWindow4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow4]));
			w3.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.chatEntry = new global::Gtk.Entry ();
			this.chatEntry.CanFocus = true;
			this.chatEntry.Name = "chatEntry";
			this.chatEntry.IsEditable = true;
			this.chatEntry.ActivatesDefault = true;
			this.chatEntry.InvisibleChar = '•';
			this.hbox3.Add (this.chatEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.chatEntry]));
			w4.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.chatSendButton = new global::Gtk.Button ();
			this.chatSendButton.CanDefault = true;
			this.chatSendButton.CanFocus = true;
			this.chatSendButton.Name = "chatSendButton";
			this.chatSendButton.UseUnderline = true;
			this.chatSendButton.Label = global::Mono.Unix.Catalog.GetString ("_Send");
			this.hbox3.Add (this.chatSendButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.chatSendButton]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox5.Add (this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.GtkAlignment3.Add (this.vbox5);
			this.frame1.Add (this.GtkAlignment3);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Chat</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel7;
			this.hpaned2.Add (this.frame1);
			this.vbox3.Add (this.hpaned2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hpaned2]));
			w10.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox ();
			this.hbuttonbox3.Name = "hbuttonbox3";
			this.hbuttonbox3.Spacing = 6;
			this.hbuttonbox3.BorderWidth = ((uint)(3));
			this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.startGameButton = new global::Gtk.Button ();
			this.startGameButton.CanDefault = true;
			this.startGameButton.CanFocus = true;
			this.startGameButton.Name = "startGameButton";
			this.startGameButton.UseUnderline = true;
			this.startGameButton.Label = global::Mono.Unix.Catalog.GetString ("Start _Game");
			this.hbuttonbox3.Add (this.startGameButton);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.startGameButton]));
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.disconnectButton = new global::Gtk.Button ();
			this.disconnectButton.CanFocus = true;
			this.disconnectButton.Name = "disconnectButton";
			this.disconnectButton.UseStock = true;
			this.disconnectButton.UseUnderline = true;
			this.disconnectButton.Label = "gtk-disconnect";
			this.hbuttonbox3.Add (this.disconnectButton);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.disconnectButton]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.endSessionButton = new global::Gtk.Button ();
			this.endSessionButton.CanFocus = true;
			this.endSessionButton.Name = "endSessionButton";
			this.endSessionButton.UseUnderline = true;
			this.endSessionButton.Label = global::Mono.Unix.Catalog.GetString ("_End Session");
			this.hbuttonbox3.Add (this.endSessionButton);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.endSessionButton]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox3.Add (this.hbuttonbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbuttonbox3]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.chatSendButton.HasDefault = true;
			this.Show ();
			this.DestroyEvent += new global::Gtk.DestroyEventHandler (this.OnDestroyEvent);
			this.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnFocusInEvent);
			this.chatSendButton.Clicked += new global::System.EventHandler (this.OnChatSendButtonClicked);
			this.startGameButton.Clicked += new global::System.EventHandler (this.OnStartGameButtonClicked);
			this.disconnectButton.Clicked += new global::System.EventHandler (this.OnDisconnectButtonClicked);
			this.endSessionButton.Clicked += new global::System.EventHandler (this.OnEndSessionButtonClicked);
		}
	}
}
